### ISSUE TITLE
Want to add the option to customize the image folder

### ISSUE THREAD

**Issue by akimolll** [noatpad/obsidian-banners#10]
When there are too many attachments, it becomes difficult to select images. Can you add setting options to allow users to customize any folder as an image folder.Thank you very much. The plug-in is great.

**Comment by noatpad** [comment]
Oh? When you say difficult, you mean as in there's latency when typing into that modal? I'm experiencing a bit of that in my personal vault, but upon testing it a little, the slowdown is actually coming from having to render a ton of images at once.

Adding an option to specify a folder is a good idea to only select certain images, but to help with the slowdown (because I can see the same issue arise in a dedicated folder too), I can also add settings to limit how many results to display in the modal at once and disable the preview images altogether.

Gonna work on this for today, so merci for the heads up!

**Comment by akimolll** [comment]
The theme has always been great. It doesn't have any problems. But I think when many people have many images, it will become difficult to find the right image. If you can allow users to put images in custom folders, this will make things easier.

**Comment by akimolll** [comment]
I updated it, it succeeded! Efficient speed! 🙀🙀🙀
