### ISSUE TITLE
Problem with image position

### ISSUE THREAD

**Issue by phaalonso** [noatpad/obsidian-banners#11]
![image](https://user-images.githubusercontent.com/26033899/134101081-9aa6ce24-3676-432c-a7c5-c62200b58fb9.png)
![image](https://user-images.githubusercontent.com/26033899/134101095-087c9eba-9352-407e-b0a9-b910b197b8fb.png)

**Comment by phaalonso** [comment]
There seems to be some incompatibility, disabling [Copy byttons for code blocks](https://github.com/jdbrice/obsidian-code-block-copy) fixed the width problem.

![image](https://user-images.githubusercontent.com/26033899/134101374-3023266b-26e7-4345-8e6f-a0c947e38798.png)

**Comment by noatpad** [comment]
Ah yeah, this is a known issue for plugins that modify code blocks in a specific way. It's already mentioned in #4, but basically, since I attach the banner to the frontmatter (which acts like a code block in the preview view) with some styling, any plugin that uses their own styling can clash with mine, & it messes things up from there. Unfortunately I (currently) have no way to apply the banner outside of the frontmatter block, so the best mitigation would be to have the other plugin ignore this plugin's styling.

As a hacky workaround though (since I messed with that plugin a little bit), you can create and enable a small CSS snippet with this:

```css
.obsidian-banner-wrapper.has-copy-button {
	position: initial;
}
```

And it should put the banner back into place, with a copy button that's a tad misleading on the top right, so hopefully that's an alright workaround for now

**Comment by noatpad** [comment]
Gonna close this due to inactivity
