### ISSUE TITLE
[BETA] Allow icon next to the inline title

### ISSUE THREAD

**Issue by Lisandra-dev** [noatpad/obsidian-banners#123]
Hello!
I tried without success in CSS, so… I want to have the icon next to the inline title, like Make.MD does:

Screen from Make.MD : 
![image](https://github.com/noatpad/obsidian-banners/assets/30244939/1ae55008-fc55-4394-9c06-097ca1b99268)

Actually:
![image](https://github.com/noatpad/obsidian-banners/assets/30244939/28f99ad1-d462-4056-8e99-a7c3fe9d8eea)

**Comment by noatpad** [comment]
This should already be possible with the `banner_icon` and the `banner_header` field! Is this that (and if so, maybe it's a theme conflict?) or are you injecting the icon in there somehow?

**Comment by Lisandra-dev** [comment]
Yeah but, I don't want to use the banner header, as I have already in-line title... It will create redondance + need to set the properties manually? :<

**Comment by noatpad** [comment]
For that, you can set `banner_header` to a Checkmark property and checked (though in the next beta release, it will be an empty string/text value because of #121), that'll automatically set the header to be the filename like how Obsidian's inline titles work.

The reason why `banner_header` exists is because I can't easily nor reliably edit elements in Obsidian's native inline title elements, and that's due to what Obsidian runs behind the scenes. So the `banner_header` is sorta like a replacement to it, but works closely with banners and icons

**Comment by Lisandra-dev** [comment]
Oh I see!
Thank you for the explanation (in #121 :))

**Comment by Aeases** [comment]
just out of curiosity, would it be possible to use css to put a emoji icon right before the Inline title with the ::before pseudo element?
