### ISSUE TITLE
Bug: Not compatible with some themes - Yin and Yang

### ISSUE THREAD

**Issue by bhickta** [noatpad/obsidian-banners#3]
![image](https://user-images.githubusercontent.com/61617746/132078297-5a024439-8ba4-45dc-af90-2a503e6e4657.png)
As it can be seen above, the test on the page is not showing below the banner, instead it is over the banner

* Note: Used Garbel text plugin to hide my text

**Comment by firinael** [comment]
I think that's something us CSS themers will have to fix. Contact @chetachi to see if there's anything she can do about it.

**Comment by noatpad** [comment]
Yeah, I checked, & it looks like the theme clashes with the styling the plugin uses. I could add a higher specificity, but another theme could have the same problem if they have one that's even higher. There's also adding `!important`, but I wanna refrain from doing that (though I could add a toggleable setting for that, just in case).

For now, it might be best to have the themes take it into account in their styling. I took a look at the Yin and Yang themes, and I believe the culprit line is this one:

https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme/blob/main/obsidian.css#L3600

That line would just need to exclude `.obsidian-banner-wrapper` for this rule

**Comment by noatpad** [comment]
Probably good to mention here, but the Yin and Yang theme had pushed a couple of changes to fix the incompatibility issue with this plugin, so it should be good to close this issue now.

If other themes happen to have a styling clash with the plugin, it'd probably be good to put an issue on the theme's repo since it's probably better to avoid overwriting styles from that level
