### ISSUE TITLE
Recent update fails to load

### ISSUE THREAD

**Issue by anvimea** [noatpad/obsidian-banners#41]
I updated the plugin (via the community store) and the Banner plugin automatically turned itself off. Attempts to turn it back on bring up the "Failed to load plugin obsidian-banners" prompt. 

Didn't do too much testing to see if there's a conflict but I tried disabling all my other plugins, it didn't help.

**Comment by RyzenFromFire** [comment]
Second this, just saw the update, tested it out, same error message. Tested in a (mostly) clean vault and it still doesn't work.

**Comment by noatpad** [comment]
Oh? Hold on, lemme see if something's up with it. I tried updating normally with my regular vault, & it loaded up fine; but maybe it has something to do with my version...

**Comment by spindensity** [comment]
The same problem with obsidian 0.13.23.

**Comment by noatpad** [comment]
I can't seem to reproduce it, and I can't seem to downgrade to the regular version since I have the insider build (but to my knowledge, this should work with the latest public version).
In case anyone wants to try, this is the same plugin but un-minified, so it can probably give me a better error log 

[main.js.zip](https://github.com/noatpad/obsidian-banners/files/8191936/main.js.zip)

**Comment by noatpad** [comment]
OH, I think I found the problem, and it's darn ESBuild that messed me up ashjgbaasgaf. Hotfix coming up in a few minutes hopefully

**Comment by noatpad** [comment]
Okay so ESBuild's newer version wasn't compatible with the current public version of Obsidian. Hotfix is now up: https://github.com/noatpad/obsidian-banners/releases/tag/1.3.1

Do tell if it's working now or still presenting issues

**Comment by spindensity** [comment]
It works now, thanks.

**Comment by anvimea** [comment]
Works now! Will close this.
