### ISSUE TITLE
publish.css version of plugin for upload

### ISSUE THREAD

**Issue by Oblique82** [noatpad/obsidian-banners#56]
This is such a great plugin and I would love to be able to have the banner on the notes I publish

I am not proficient with any programming - but I wonder if there is any way to make this work with custom CSS?

**Comment by noatpad** [comment]
Hihi! So unfortunately, plugins are incompatible with "Published" notes, so the logic won't work. It's been mentioned that it's something on Obsidian's roadmap, but currently it's not possible.

You can maybe add some custom CSS to mimic it and inject your banner image there, but it's probably more trouble than it's worth because what determines the banner image is the CSS instead of the note itself. And as far as I'm aware, you can only upload a single `publish.css` file, so it would affect all notes at that point.
